src/resources/lib/modules/system.py
`xbmc.PLAYER_CORE_AUTO` doesn't exist anymore.
=> fix updating by dropping an old kodi convention

Makefile, language/English/strings.po, src/oe.py, src/resources/lib/modules/bluetooth.py, src/resources/lib/modules/services.py, src/resources/lib/modules/system.py
This PR contains changes to bluetooth pairing and some minor fixes we have been using in RasPlex for some time
- Adds a new 'Pair' context menu entry for bluetooth devices that is dependent on bluez's 'Paired' property
- Slight modification to the authorize, pin and passkey dialogs and when the busy dialog is shown
- Non-debug log entries is always logged
- Use existing language for backup/restore dialogs
- Changes title on soft/hard reset dialog
=> Rework bluetooth pairing

src/resources/lib/modules/connman.py
This PR prevents empty timeserver values from being saved to connman's global settings, fixes:
A default Timeservers property for a connman service:
```Timeservers = [ 0.pool.ntp.org, 1.pool.ntp.org, 2.pool.ntp.org, 3.pool.ntp.org ]```
After one of the `Network -> NTP Servers -> Timeserver` settings has been opened and closed without entering any value:
```Timeservers = [ , 0.pool.ntp.org, 1.pool.ntp.org, 2.pool.ntp.org, 3.pool.ntp.org ]```
The empty value prevents the remaining fallback timeservers from being used.
=> Only use non-empty values for global timeservers

src/resources/lib/modules/system.py
This isn't really needed as we should always have keymaps installed, but I noticed it in my dev environment where I didn't have any keymaps.
=> get_keyboard_layouts should return three values

language/English/strings.po, src/oe.py, src/resources/lib/modules/system.py, src/resources/lib/oeWindows.py
should be good to go, let me know if the strings make sense.
=> allow using custom update channels

src/resources/lib/modules/system.py
See: http://forum.kodi.tv/showthread.php?tid=269815&pid=2437666#pid2437666
`shutil.move()` will perform an `os.rename()` when the source and destination file systems are the same, and a copy and delete when different.
=> system update - fix cross-device linking

language/English/strings.po, src/defaults.py, src/resources/lib/modules/services.py
This cheeses it a little bit by abusing the `/sys/class/lirc/lirc0/uevent` to fake a remove or add event to udev.
This is needed because the systemd service is dynamic as it is called by a udev rule that matches certain files/modules to run the `lircd@.service`
So it's not possible to start/stop the `lircd@.service` directly. This calls a remove/add event which will trigger udev to start/stop the specific systemd `lircd@.service` file
Please take a look at the strings and capitalization.
This is needed with https://github.com/LibreELEC/LibreELEC.tv/pull/913
=> lircd: allow disabling

src/resources/lib/modules/system.py
I'm not 100% happy about this but it does work. It does it in a workaround way though
Instead of tracking the object all the way through it first uses the regex on the filenames to get the short filenames, then when one of the short filenames is chosen it takes that short name and scans the list of long filenames to find a match, which may not be 100%. We have set filenames though and it shouldn't be a problem I don't think.
This was the only way I could think of doing it because `self.struct['update']['settings']['Build']['values']` needs to be a list, so I cannot pass a dict to it to track a prettyname and a filename for one object.
@MilhouseVH please include this in your testbuilds, it will work for you already because you include `prettyname_regex` already in your releases.json
=> use prettyname_regex to show shortname in update menu

src/oe.py, src/resources/lib/modules/bluetooth.py, src/service.py
This PR fixes:
- Screensaver never being activated when `Enable Standby` is activated for a bluetooth device
- `Enable Standby` devices not being disconnected when the screensaver is activated
https://forum.libreelec.tv/thread-1442.html
=> fix bluetooth standby when screensaver is activated

src/resources/lib/modules/system.py, src/resources/lib/oeWindows.py
Rather than sort the list of available builds by the displayed name, we should sort the available builds by the reverse order in which they appear in the `releases.json` file (ie. n, n-1, n-2, ... 0).
This PR prevents a build such as `#0101` (from 2017) being listed last in the list and `#1231` (from 2016) being listed first, which happens because we are sorting the list into reverse sort order based on the displayed list value - `#0101` is a more recent build than `#1231`, and should be listed first.
In `releases.json` we have:
```
{
"0": {"file": {"sha256": "476425330acdae7227082009dbc1b13c549cfe3485b623698493c376351161b6", "name": "LibreELEC-Generic.x86_64-8.0-Milhouse-20160331012541-#0330-g46e67b7.tar", "size": "215193600"}},
"1": {"file": {"sha256": …
```
=> Add (and display) pretty names in release order - not name order

Makefile
#49 added file-name brace expansion:
```
cp textures/$(DISTRONAME)/*.{png,jpg} $(BUILDDIR)/$(ADDON_NAME)/resources/skins/Default/media/default
```
Brace expansion is a bash-ism. By default, when the SHELL variable is not set, `make` will use `/bin/sh` as the shell, see [manual](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html).
Consequently after #49, `make` fails:
```
BUILD    LibreELEC-settings (target)
Executing (target): make DISTRONAME=LibreELEC ROOT_PASSWORD=libreelec
make[1]: Entering directory '/home/neil/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-8.0-devel/LibreELEC-settings-ede7dc8'
mkdir -p build/service.libreelec.settings/resources/skins/Default/media/default
mkdir -p build/service.libreelec.settings/resources/skins/Default/media/icons
mkdir -p …
```
=> Makefile: Need /bin/bash for bashisms

src/resources/lib/modules/bluetooth.py
This PR restores the old *Trust and Connect* option that has been missing since #18 for devices that was trusted but not paired. The new option was renamed to *Connect* and is only shown when a device is trusted.
Thanks @MilhouseVH for pinpointing when the issue started!
=> bluetooth: add missing 'Connect' option when device is Trusted

src/defaults.py
This change moves the initial update check request to https to avoiding an initial http request that is 301 redirected and results in a second (https) request.
NB: no bump to changelog/makefile in this PR as #58 removes the need for that in master.
=> settings: use https for update checks

src/resources/lib/modules/system.py
LE should default enable auto-update so our userbase is herded towards the current release with the latest bug and security fixes. This will reduce our support effort and lower risk for users. In the past this was impossible because the high rate of change (and untested change) in OE release branches resulted in maintenance releases that frequently broke as much stuff as they fixed. LE is proving to be much more responsible and conservative about maintenance release content, and IMHO it's time to do this.
This also needs exposing in the first-run wizard so that nervous people can opt-out, but I need to learn some Python before I tackle that change :)
CLARIFICATION: This will allow us to push 9.0.1, 9.0.2 etc. or 9.0.2 to 9.2.0 and have the majority of users update track new releases. …
=> change default from manual-update to auto-update

src/default.py
=> service: fix icon path

src/oe.py, src/resources/lib/modules/bluetooth.py
Disabling Bluetooth will result in the following error:
```
23:54:04.581 T:1503253392   DEBUG: ## LibreELEC Addon ## services::init_bluetooth ## enter_function
23:54:04.581 T:1503253392   DEBUG: ## LibreELEC Addon ## oe::set_busy ## __busy__ = 1
23:54:04.581 T:1503253392   DEBUG: ## LibreELEC Addon ## services::set_value ## enter_function
23:54:04.581 T:1503253392   DEBUG: ## LibreELEC Addon ## services::set_value ## exit_function
23:54:04.581 T:1503253392   DEBUG: ## LibreELEC Addon ## oe::set_service ## enter_function
23:54:04.581 T:1503253392   DEBUG: ## LibreELEC Addon ## oe::set_service::service ## 'bluez'
23:54:04.581 T:1503253392   DEBUG: ## LibreELEC Addon ## oe::set_service::options ## {}
23:54:04.581 T:1503253392   DEBUG: ## LibreELEC Addon ## oe::set_service::state ## 0 …
```
=> bluetooth: avoid race during disable

src/resources/lib/modules/system.py
instead of hard coded "/storage"
Backports #82
=> Backup: get free space of selected folder

src/resources/lib/modules/connman.py
Enabling Wifi tethering always defaults to the password: libreelec. Since the SSID defaults to LibreELEC-AP it is a pretty simple password to guess. 
Now a 10 character long random (digits and letters only) string is generated by default. Not sure about the 10 characters is too long or too short.
=> connman.py: More secure default password for tethering

language/English/strings.po, src/oe.py, src/resources/lib/modules/system.py, src/resources/lib/oeWindows.py
See: https://github.com/LibreELEC/LibreELEC.tv/pull/2228
If "safe mode" is activated (contents of `/storage/.config/boot.status` will be `SAFE` rather than `OK`) then the following landing page will be shown:
In addition this PR adds the following enhancements:
1. Added a second "Submit log" option which uploads the latest `kodi_crash.log` rather than the regular `kodi.log`
2. When in "safe mode", the uploaded logs will be read from the `.kodi.FAILED` folder
3. I've updated the help text string associated with the existing "Submit log" item, as it was not accurate (will need translating)
4. I've added x86 boot file support to the uploaded logs (syslinux.cfg etc.)
5. The "Boot mode" (`EFI` or `BIOS`) will be recorded in the log (second line) for `x86_64` systems
6. The addon will no longer …
=> add safe mode support

src/resources/lib/oeWindows.py
When fresh installing LibreELEC Kodi tries to update repositories at first start but may fail because  network is not yet configured (i.e. WLAN). Afterwards it is not possible to install any addon without manually selecting "Check for updates".
Work around the issue by triggering repository updates at end of setup wizard.
There have been several reports in the forum, latest [here](https://forum.libreelec.tv/thread/10851-nothing-works-to-install/).
=> Trigger update repositories at end of wizard

language/Bulgarian/strings.po, language/Czech/strings.po, language/Dutch/strings.po, language/English/strings.po, language/French/strings.po, language/German/strings.po, language/Italian/strings.po, language/Lithuanian/strings.po, language/Norwegian/strings.po, language/Portuguese (Brazil)/strings.po, language/Russian/strings.po, language/Swedish/strings.po, src/defaults.py, src/resources/lib/modules/services.py
This is no longer needed when https://github.com/LibreELEC/LibreELEC.tv/pull/2341 gets merged - lirc start is then only controlled by presence of a user lircd.conf file
=> remove lirc enable/disable setting

language/Bulgarian/strings.po, language/Czech/strings.po, language/Dutch/strings.po, language/English/strings.po, language/French/strings.po, language/German/strings.po, language/Italian/strings.po, language/Lithuanian/strings.po, language/Norwegian/strings.po, language/Portuguese (Brazil)/strings.po, language/Russian/strings.po, language/Swedish/strings.po
I've manually edited the non-English language files - these will need to be pushed to Transifex.
=> sprunge.us: replace by ix.io

language/Bulgarian/strings.po, language/Czech/strings.po, language/Dutch/strings.po, language/English/strings.po, language/French/strings.po, language/German/strings.po, language/Italian/strings.po, language/Lithuanian/strings.po, language/Norwegian/strings.po, language/Portuguese (Brazil)/strings.po, language/Russian/strings.po, language/Swedish/strings.po
I've manually edited the non-English language files - these will need to be pushed to Transifex.
=> sprunge.us: replace by ix.io [backport]

language/English/strings.po, src/resources/lib/modules/connman.py
With following changes we can have translations for the different rule values. Also there is no more on/off switch. You can just choose between Off, Public, Home and Custom. Custom is conditional and only appears in /storage/.config/iptables/rules.v* exist.
I'm not sure about the english strings and messages.
=> connman: Language support for Firewall Rules

src/resources/lib/modules/system.py
current get_folder_size() function has some issues:
- It does follow symbolic links what leads to few issues: 1) it goes outside of BACKUP_DIRS 2) it counts filesize more then one time for the same file and ignores actual size of a symlink
- It does not count directory size, like directory itself (usually it's 4096 bytes)
- It does not know anything about hardlinks, so single inode can be summarized multiple times 
do_backup function should use f_frsize rather than f_bsize to calculate the right size in bytes:
statvfs.F_BSIZE - Preferred file system block size
statvfs.F_FRSIZE - Fundamental file system block size
=> backup folder size fix

src/resources/lib/modules/connman.py
The new iptables setting could only be turned off temporarily. This PR fixes the issue.
Thanks @HiassofT for reporting the issue.
=> iptables: Fix "off" setting

src/resources/lib/modules/system.py
With the switch to libinput/libxkbcommon both X and non-X keyboard layouts
are now available but only the non-X layouts should be loaded when both are
present in the system (eg. RPi/RPi2).
Non-X layouts are not available in X-based systems (ie. Generic) while X-layouts are available.
This is dependent on https://github.com/LibreELEC/LibreELEC.tv/pull/2654 which introduces libinput and libxkbcommon. If we merge this before https://github.com/LibreELEC/LibreELEC.tv/pull/2654 then I'll add the bump in the PR. Leave this for a few days so I can test it in nightly builds.
=> Favour non-X keyboard layouts over X

src/oe.py, src/resources/lib/modules/bluetooth.py, src/resources/lib/modules/connman.py
Attempts to open the `busydialog` now result in the following message (and no busy dialog is shown):
```
09:24:31.634 T:3987755888 WARNING: addons must not activate DialogBusy
```
=> remove all attempts to open/close the busydialog which is now verboten

src/resources/lib/modules/bluetooth.py, src/resources/lib/modules/connman.py
Solves errors on shutdown:
```
ERROR: ## LibreELEC Addon ## bluetooth::monitor::remove_agent ## ERROR: (AttributeError("'NoneType' object has no attribute 'remove_from_connection'",))
ERROR: Traceback (most recent call last):
File "/home/neil/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/LibreELEC-settings-659afa8/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/bluetooth.py", line 738, in remove_agent
AttributeError: 'NoneType' object has no attribute 'remove_from_connection'
```
Kodi log: [http://ix.io/1kzb](http://ix.io/1kzb)
=> fix variable reset in remove_agent() functions

src/resources/lib/modules/system.py
Mask the bottom 26 bits of the RPi revision code as that's all we want. Anything else is garbage (eg. `80a020d3`).
=> We only want bits 0:25 for revision codes

language/English/strings.po, src/resources/lib/modules/services.py
This adds the suggestion to change the default password if SSH is enabled during the first run wizard.
It should cover all scenarios of a user starting to change the password, entering something that isn't valid, having the option to change try again or use default or changing their mind and cancelling back to the default.
=> add ssh passwd change to wizard

skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml
This change 
- removes the big logo from the top right
- changes the about text to be max 3 lines
- moves the "support", "documentation", "code" and "donation" texts a bit more to the top
The reason is, that with the logo we loose too much space and the bottom of the text overlays the blue separator line.
=> reorganize about section

skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml
We have enough space now, so let's show the complete version at the Milhouse builds and also let´ s use the same space for the other sections.
=> avoid truncating of version number

src/resources/lib/modules/updates.py
This change will force the available builds to update when the button is selected.
Currently the system only updates available builds when a channel is selected or when the system is rebooted.
=> update available builds when button selected

src/resources/lib/modules/bluetooth.py
This PR fixes duplicate bluetooth devices being listed after reopening add-on.
=> Fix duplicate bluetooth devices

src/resources/lib/modules/connman.py
This PR does 4 things:
- Fix warnings from use of tabs.
- Log D-Bus error "Did not receive a reply"  silently.
- Fix intermittent connection issues and possible Kodi crash
- Only run initialize_agent if its not already done
=> Fixes for connman module

src/resources/lib/modules/bluetooth.py
This reverts the previous PR #124 and properly fixes the bluetooth issue. 
sorry guys i missed the fact i broke stuff but i have fixed it properly now.
=> Properly fix duplicate bluetooth devices

src/resources/lib/modules/system.py, src/resources/lib/modules/updates.py
This cleans up code that was duplicated when Updates was split from System into its own section and (re)adds Amlogic flags adapted to also support Allwinner and Rockchip devices if the `dtname` helper script is present. We can now report `pine64,pine-h64` and `khadas,vim` or `firefly,roc-rk3328-cc` to gain visibility on board use under SoC catch-all projects like H3 and RK3399. I'm still figuring out the best package to add `dtname` via, but will send a PR for that to main repo in the near future.
=> fix missing flags

language/resource.language.en_gb/strings.po, src/defaults.py, src/resources/lib/modules/system.py, src/resources/lib/modules/updates.py
Support https://github.com/LibreELEC/LibreELEC.tv/pull/3729
This option will be hidden on systems other than RPi4 (ie. any system that lacks `/usr/lib/libreelec/rpi-flash-firmware`).
It does not automatically reboot once enabled - I figure we can extend this to support updating of the VIA USB firmware with a second option. That way users can choose to update one or the other, or both, and *then* reboot, at which point one or both will be updated.
=> Add support for RPi4 Bootloader flashing

src/resources/lib/modules/updates.py
Requested by @chewitt.
Before:
After:
Order is: `<name>`(asc)-`<version>`(desc)
Unfortunately the current item (ie. `Milhouse-9.80`) is always listed first - my add-on GUI foo is pretty limited, but there doesn't seem to be much we can do about that. Suggestions welcome...
=> Sort update channels (trains)

language/resource.language.en_gb/strings.po, src/resources/lib/modules/system.py, src/resources/lib/modules/updates.py
This adds support for parsing the machine-readable output from the RPi flashing script.
Leaving as draft until changes accepted upstream.
=> RPi4 Flashing: parse machine output

skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml
`videolibrary` is removed by https://github.com/xbmc/xbmc/pull/9886 (no longer valid since Krypton) and currently produces this error when entering the Settings addon:
```
2019-09-18 23:24:24.208 T:1931829264   ERROR: Window Translator: Can't find window videolibrary
```
=> Stop referencing non-existant window

src/oe.py, src/resources/lib/modules/updates.py
This adds `RPI_CPU_VER`:
`0`=`BCM2835` (ARM1176 - RPi0/RPi1)
`1`=`BCM2836` (Cortex-A7 - RPi2)
`2`=`BCM2837` (Cortex-A53 - RPi2/RPi3/RPi3+)
`3`=`BCM2838` (Cortex-A72 - RPi4)
Use `RPI_CPU_VER` to enable/disable the RPi Flashing options, ensuring we disable RPi Flashing whenever the RPi4 image is installed on RPi2/RPi3 hardware.
=> Support RPi CPU detection, enable firmware updates only for RPi4

src/defaults.py, src/resources/lib/oeWindows.py
LE settings changes for https://github.com/LibreELEC/LibreELEC.tv/pull/3936
If the /dev/.kernel_ipconfig marker file is present the connman module is disabled (and thus the network settings aren't shown)
=> disable network configuration settings when using kernel ip config / netboot

src/resources/lib/oeWindows.py, src/service.py
If Kodi is shutdown when the First Run Wizard is active the following exception occurs:
```
2019-11-16 03:24:54.690 T:1929  NOTICE: stop dvd detect media
2019-11-16 03:24:54.692 T:1951   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: 'wizard' object has no attribute 'visible'
Traceback (most recent call last):
File "/usr/share/kodi/addons/service.libreelec.settings/service.py", line 98, in <module>
if oe.winOeMain.visible == True:
AttributeError: 'wizard' object has no attribute 'visible'
-->End of Python script error report<--
2019-11-16 03:24:59.693 T:1929   ERROR: CPythonInvoker(0, …
```
=> service.py: wizard window does not have visible attribute

src/resources/lib/modules/services.py
Fix issue reported on the [forum](https://forum.kodi.tv/showthread.php?tid=343069&pid=2919489#pid2919489).
Switching to `text` mode avoids the hassle of dealing with bytes as everything we read/write will be a string.
Buffering is disabled by setting `bufsize=0` which means we don't need to flush stdin (which can fail when re-entering the password a second time if `passwd` has already bailed due to a weak password).
=> ssh password: switch to text mode, disable buffering

src/oe.py, src/resources/lib/modules/system.py
As noted on the [forum](https://forum.kodi.tv/showthread.php?tid=343069&pid=2918914#pid2918914), the update download speed in Kodi is significantly lower than the user is able to achieve at the command line using `curl`.
This is because we update the progress dialog up to 80 times a second, although the actual rate at which we update is dependent on the connection speed (and also the 32KB chunk size). A high-ish download speed combined with the small chunk size results in a high rate of dialog updates.
My own internet connection speed is 1Gbps, and on an i5 Skylake NUC `curl` downloads a tar file from the download server to NVMe storage at the full 100MB/s, but Kodi only achieves 22.5MB/s as it is updating the dialog 70-75 times a second.
Increasing the chunk size would reduce the number …
=> improve download performance on fast connections

src/oe.py
This masks the input of the PIN when access to LibreELEC Settings is locked and PIN entry is required.
Depends on https://github.com/xbmc/xbmc/pull/17661
=> Mask PIN input

src/resources/lib/modules/updates.py
This adds stats flags for some additional SoC types to the settings add-on. Samsung (aka Exynos aka Odroid XU4) is still a WIP effort, but IMHO harmless to add.
=> use device-tree flags for NXP/Qualcomm/Samsung devices

src/oe.py, src/resources/lib/modules/bluetooth.py, src/resources/lib/modules/connman.py, src/resources/lib/modules/system.py, src/resources/lib/modules/updates.py, src/resources/lib/oeWindows.py
https://github.com/xbmc/xbmc/pull/17789
=> Remove xbmc.abortRequested flag

src/oe.py, src/resources/lib/oeWindows.py
As reported in the [forum](https://forum.libreelec.tv/thread/21832-libreelec-wizard/) Language selection in nightly builds is crashing when selecting any language with non-ASCII UTF-8 characters.
Open the file in UTF-8 mode and remove function str.decode('UTF-8') not existing in Python 3.
Second commit is fixing dialog title from "Enable LibreELEC Settings PIN Lock" to "Language:"
=> Fix wizard language selection

src/resources/lib/oeWindows.py
Replace "Enable LibreELEC Settings PIN Lock" with "Language:"
Partial backport of #167
=> Fix title (msg ID) of wizard language select dialog

src/resources/lib/modules/connman.py, src/resources/lib/oeWindows.py
When i.e. Default Gateway is omitted the address is not set [(see forum)](https://forum.libreelec.tv/thread/22441-can-not-manual-set-ip-address/). The error reported by connman is `Invalid arguments`:
```
2020-08-07 00:29:33.440 T:139995591505664   ERROR: ## LibreELEC Addon ## connmanService::save_network ## ERROR: (DBusException('Invalid arguments',))
2020-08-07 00:29:33.442 T:139995591505664   ERROR: Traceback (most recent call last):
File "/storage/.kodi/addons/service.libreelec.settings/resources/lib/modules/connman.py", line 426, in save_network
self.service.SetProperty(dbus.String(category), value)
File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: …
```
=> Fix manual IPv4 configuration 

src/resources/lib/modules/connman.py, src/resources/lib/oeWindows.py
When i.e. Default Gateway is omitted the address is not set [(see forum)](https://forum.libreelec.tv/thread/22441-can-not-manual-set-ip-address/). The error reported by connman is `Invalid arguments`:
```
2020-08-07 00:29:33.440 T:139995591505664   ERROR: ## LibreELEC Addon ## connmanService::save_network ## ERROR: (DBusException('Invalid arguments',))
2020-08-07 00:29:33.442 T:139995591505664   ERROR: Traceback (most recent call last):
File "/storage/.kodi/addons/service.libreelec.settings/resources/lib/modules/connman.py", line 426, in save_network
self.service.SetProperty(dbus.String(category), value)
File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: …
```
=> Fix manual IPv4 configuration [le92]

src/resources/lib/modules/updates.py
Error reported in the [forum](https://forum.libreelec.tv/thread/22609-libreelec-update/?postID=144324#post144324). Auto update is not working in LibreELEC 9.2.
Beside #164 there is a crash in the notify function when using i.e. Hungarian language because of missing unicode strings.
There is no fix needed in master due to the different string handling in Python 3.
=> auto update: use unicode strings for notify()

src/oe.py
Use unicode labels in ProgressDialog to fix crash when using non ASCII UTF-8 characters.
The error has been reported in the forum [here](https://forum.libreelec.tv/thread/22145-can-t-update-v9-2-1-to-v9-2-3-through-gui-in-czech-language/) and [here](https://forum.libreelec.tv/thread/22511-manual-update-doesn-t-work-in-bulgarian-language/).  Manual update did not work.
``` text
2020-06-08 06:17:03.165 T:2962219888   ERROR: ## LibreELEC Addon ## oe::download_file(http://releases.libreelec.tv/LibreELEC-RPi4.arm-9.2.3.tar, /storage/.kodi/temp/update_file) ## ERROR: (UnicodeDecodeError('ascii', 'Jm\xc3\xa9no souboru: ', 2, 3, 'ordinal not in range(128)'))
2020-06-08 06:17:03.166 T:2962219888   ERROR: Traceback (most recent call last):
File …
```
=>  Fix crash in ProgressDialog

src/oe.py, src/resources/lib/modules/about.py, src/resources/lib/modules/bluetooth.py, src/resources/lib/modules/connman.py, src/resources/lib/modules/services.py, src/resources/lib/modules/system.py, src/resources/lib/modules/updates.py, src/resources/lib/modules/xdbus.py, src/resources/lib/oeWindows.py, src/service.py
With Kodi PR [Remove LOGNOTICE and LOGSEVERE from python addons and kodi](https://github.com/xbmc/xbmc/pull/18346) the log level numbers will change. Fix setting addon by using symbolic log levels.
Most work was done by:
```
find src -name "*.py" -print0|xargs -0 sed -i 's/\([^ ]*\.\)\?\(dbg_log(.*, \)0)/\1\2\1LOGDEBUG)/'
find src -name "*.py" -print0|xargs -0 sed -i 's/\([^ ]*\.\)\?\(dbg_log(.*, \)1)/\1\2\1LOGINFO)/'
find src -name "*.py" -print0|xargs -0 sed -i 's/\([^ ]*\.\)\?\(dbg_log(.*, \)2)/\1\2\1LOGWARNING)/'
find src -name "*.py" -print0|xargs -0 sed -i 's/\([^ ]*\.\)\?\(dbg_log(.*, \)4)/\1\2\1LOGERROR)/'
find src -name "*.py" -print0|xargs -0 grep -ne 'dbg_log(.*[^)]$'
```
This PR needs #160 to be committed first.
=> Use symbolic log level definitions instead of numbers

src/resources/lib/modules/system.py
Fix not using UTF-8 error when loading keyboard info. A fatal error is generated after Python 3.8 update:
```
2020-09-16 10:29:46.260 T:661     FATAL <general>: ## LibreELEC Addon ## system::get_keyboard_layouts ## ERROR: (UnicodeDecodeError('ascii', b'<?xml ...
```
Log: https://github.com/LibreELEC/service.libreelec.settings/files/5233919/kodi.log
=> system.py: fix reading UTF-8 keyboard layouts in Python 3.8

src/oe.py, src/resources/lib/modules/system.py
Three minors from my build branch:
xbmc.translatePath -> xbmcvfs.translatePath is a K19 change; resolves a deprecation warning in the log
system reset file flags simply need to exist as files, not have anything written to them
The backup dir creation logic was doing:
If dir doesn't exist, create it, otherwise delete it and create it.
This is:
If it exists, delete it, then everyone creates it.
=> Assorted minor changes

src/resources/lib/modules/updates.py
This depends on https://github.com/LibreELEC/LibreELEC.tv/pull/4662 for the helper script. It will help normalise the board stats on our Pi userbase which are currently reported as SoC revision codes (more detailed, but not human friendly).
=> use dtflag helper for arm board stats

addon.xml, src/resources/lib/config.py, src/service.py
This simplifies the code of service.py
The existing logic is preserved
service.py only refers to itself
In other words, the modules being migrated to ravel are not affected by this pull request
However, some of the ideas used in this pull request and in #189 may be reused to simplify migration to ravel
Most importantly, service.py becomes legible and maintainable
=> service.py: cosmetic changes

src/default.py, src/defaults.py, src/oe.py, src/resources/lib/modules/about.py, src/resources/lib/modules/bluetooth.py, src/resources/lib/modules/services.py, src/resources/lib/modules/system.py, src/resources/lib/modules/updates.py, src/resources/lib/modules/xdbus.py, src/resources/lib/oeWindows.py, src/service.py
Python has multiple ways to combine strings and variables:
`print("Some Var's value is: %s" % SOME_VAR)`
`print("Some Var's value is: " + SOME_VAR)`
`print("Some Var's value is: {}".format(SOME_VAR))`
`print(f"Some Var's value is: {SOME_VAR}")`
(and probably some others that I haven't used)
The addon uses a blend of the first two styles. The examples above are purposefully simple, but they can get complicated to maintain. This PR converts most usage to the 4th option, known as an f-string, which is easiest to read in my opinion. Functionally, they're identical so it comes down to what others prefer to use. Assuming others agree, f-strings have the added benefit of being the fastest method of formatting strings.
Draft because while this should be complete, and I've been using it since …
=> f-strings conversion

src/resources/lib/modules/updates.py
The recent change to use `dtflag` works nicely but stats show a number of unofficial ARM device projects that don't match the static `PROJECT` list. To capture these, use `ARCHITECTURE` which reads `LIBREELEC_ARCH` in `/etc/os-release` e.g. `AMLGX.arm` so we need to split the string to get the value.
=> use ARCHITECTURE instead of PROJECT for dtflags

src/oe.py
Follow up to #173 
Fix for a real error: Today log level 4 is LOGFATAL, but LOGERROR is needed here.
=> Convert overlooked numeric log levels / Move status logs from LOGERROR to LOGINFO

src/resources/lib/modules/system.py
Drop imports that aren't referenced.
Don't repeatedly define xbmcDialog as xbmcgui.Dialog().
Other minors.
=> Small cleanup pass over system.py

src/resources/lib/modules/services.py
Drop imports and variables that aren't referenced.
Use with statements for opening files.
Don't use f-strings when strings aren't being formatted.
Standardize bluetooth and obex startup on the initialize_X naming used elsewhere in the module.
Only set the state of each service once per setup.
Standardize testing of services being enabled.
=> Small cleanup of services.py

resources/lib/oe.py
Without encoding the read() will end up with **UnicodeDecodeError** when using Python 3.
=> oe: fix 'load_file' encoding for Python 3

resources/lib/modules/system.py, resources/lib/modules/updates.py
Calling xbmc.executebuildin('Reboot') from Settings addon result in deadlock in libdbus python callback.
Use `/usr/bin/systemctl --no-block reboot` instead.
Backtrace: http://ix.io/2KYC  Debug log: http://ix.io/2KYD
For the tests a minimal not functional version of the bluetooth.py module was used to avoid the typical hang on exit because of using dbus-python (deleting bluetooth.py is possible too). 
Note: calling xbmc.executebuildin('Reboot') from an addon not using dbus i.e. [script.hello.world.reboot-matrix.zip](https://github.com/LibreELEC/service.libreelec.settings/files/5771938/script.hello.world.reboot-matrix.zip) is still possible.
=> Work around deadlock when calling xbmc.executebuildin(Reboot)

resources/lib/dbus_bluez.py, resources/lib/dbus_obex.py, resources/lib/modules/bluetooth.py
This finishes up the great work done by @thoradia. They changes they made really made this easy to do (I'm not sure why they didn't finish it?).
A few comments:
- obex is updated (and should work) but there won't be any gui for the file transfer. dbussy doesn't currently have the ability to listen for signals on an interface without specifying a method name. For file transfers we want to be able to update the status during any change. I'll make an issue about this at the dbussy repo.
- I had problems with the async method calls crashing kodi. I attribute this to the fact that we are asynchronously trying to update the menu items and subsequently crash if we try to update (or delete) and item that doesn't exist. I've changed these methods to be synchronous in d3d7a78 (I'm wondering if we …
=> Bluetooth: finish moving to dbussy

resources/lib/log.py
Reimplmentation of LE 9.2 (and older) feature
Usually settings addon debug log messages are not required. When needed enable them with `DEBUG=on` in /storage/.config/kodi.conf.
=> log.py: avoid log spam, only debug log to kodi if $DEBUG is set

resources/lib/oeWindows.py
This resolves:
ERROR <general>: installaddon called with invalid number of parameters (should be: 1, is 0)
appearing in the log after using first-run wizard.
In short, if a new language hasn't been selected, don't try to change Kodi's interface language, or install a language addon pack.
Minor cleanup of variables that made this harder to read than necessary.
Tested using English and Spanish.
=> oeWindows.py: fix language pack installation after first run wizard

resources/lib/oeWindows.py
Due to a malformed releases.json, the 'Updates' menu entry in settings addon disappeared. 
In this case, `setting['values']` was None and the following error was returned: `TypeError: can only join an iterable`.
If relases.json is malformed, the settings addon should be robust on errors and not hide menu entries.
=> Check if setting is None before join

resources/lib/modules/updates.py
In the last LibreELEC nightly build, the name pattern changed from 
`LibreELEC-RPi4.arm-10.0-nightly-20210227-9c75e28.tar` to
`LibreELEC-RPi4.arm-10.0-devel-20210304145850-fa9da75.tar`
Since I use a custom update channel with a `prettyname_regex`, the regex broke and the "update" menu entry in LibreELEC settings addon completely disappeared.
This PR adds a check if regex matches and falls back to full name.
Note: I will runtime test this PR later, haven't tested yet.
=> Handle invalid regex pattern in updates

resources/lib/defaults.py, resources/lib/modules/system.py
This adds a filter (or mask) to prevent paths within BACKUP_DIRS from being backed up. The proposed filters are:
.kodi/addons/temp
.kodi/temp
.kodi/userdata/Thumbnails
The first two, I'm taking at their face value that they are indeed temporary directories and unimportant for a restoration. userdata/Thumbnails is Kodi's artwork cache. For me, this trimmed about 15MB off a backup tarball (I believe almost all attributable to the art cache).
Needs #160 to work.
=> filter certain paths from backup

resources/lib/modules/system.py
Busybox tar fail to restore all timestamps of a POSIX 1003.1-2001/pax format tar file created by python3 "tarfile". See https://forum.libreelec.tv/thread/23744-le-9-95-1-backups-are-restored-with-mtime-jan-1-1970-for-some-files-with-testcas/
The previously used gnutar format is working fine. Just force it.
The default tar format of tarfile changed with python 3.8 from gnutar to posix.  
I'm not sure whom to blame. Tarfile generated files can be successfully extracted with GNU tar and GNU tar generated files can be successfully extracted with Busybox tar.
=> system.py: backup: use gnutar format again

resources/lib/oeWindows.py
Calling xbmc.executebuiltin('UpdateAddonRepos') just trigger the repo update. The following xbmc.executebuiltin(f'InstallAddon({lang_new})') still fails to install the language addon.
We can trigger the repo update after the network is configured. The update is performed in the background while the user continue to use the wizard.
=> Wizard: call xbmc.executebuiltin('UpdateAddonRepos') early

resources/lib/oeWindows.py
When using LE's first run wizard, only attempt to switch the language if the language addon is installed. When it's not installed, write something useful to the log.
User experience in the failure case won't be great, but also won't cause errors. The wizard will change language, complete, and the interface will remain in English. Going to Settings -> Interface -> Regional afterwards will continue to change the language like normal.
=> oeWindows.py: only change language using wizard if language installed

resources/lib/defaults.py, resources/lib/modules/updates.py
This is part cleanup and part new feature.
~~The new feature is a true/false button to switch between the settings addon looking for releases.json between releases.libreelec.tv(false) and test.libreleec.tv(true). This is tested to the extent that I know it looks in the expected locations, but I do not obtain my updates this way to confirm anything past that.~~
~~This will be a draft until a brave soul tests and reports back.~~
Reduced to the cleanup portion.
=> updates.py: cleanup

resources/lib/log.py, resources/lib/modules/system.py
1) Fix possible print crash avoided with 4882595085. The debug log  and printing the folder name may crash too. See comments in commits.
2) Fix error handling in backup: do not continue on error (and create further errors in log). Remove the partial created backup file in this case.
=> backup: do not crash when print or log file and path names / fix error detection and remove failed backup

resources/lib/modules/updates.py
I tried to name the channel of my custom update channel (in my release.json) sth like `LibreELEC-10.0_(unofficial)`. When opening the settings addon, the list of selecting an channel is empty, because float cast for sort order of `10.0_(unofficial)` fails (obviously).
This MR makes channel order more robust, if channel name does not follow the naming convention `{text}`-`{float}`. Otherwise, a single broken or malicious update channel could break the update function in the addon.
I tested this on pi 4.
=> Make channel name parsing more robust

.gitignore, requirements-dev.txt, resources/lib/debug_utils.py, resources/lib/log.py, resources/lib/modules/bluetooth.py, resources/skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml
This PR introduces the following changes:
1. Fixed flickering of the text label for BT connection errors over the devices list.
2. ControlList for BT devices is re-rendered only if the actual list of devices has changed.
3. Verbose exception logging.
=> Fix Bluetooth device list

resources/lib/regdomain.py
When reading configured regulatory domain from `/storage/.cache/regdomain.conf` the two letter country code is matched against the list of country names. First entry is `NOT SET (DEFAULT)` resulting in false positive matches for NO, SE, ET, DE, AU and LT.
Add brackets (again) around the country code to fix the match.
Bug was reported in the forum:
https://forum.libreelec.tv/thread/24303-i-can-t-set-the-wireless-regulatory-domain-to-germany/
https://forum.libreelec.tv/thread/23676-libreelec-10-beta-5ghz-wifi-issue/
=> regdomain: fix reading stored country code

resources/lib/log.py, resources/lib/modules/system.py
Reported in [forum](https://forum.libreelec.tv/thread/23717-le-9-95-1-backup-reboot-libreelec-on-rp4/?postID=160400#post160400): Kodi on RPI4 may crash when rendering some Unicode characters. I was not able to reproduce the crash on Generic.
Only printing ASCII characters avoid the issue. 
Successful tested by the affected user.
---
Second commit is to fix python error:
```
ERROR <general>: */system.py:322: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
=> backup: avoid printing unicode characters beside ASCII / Fix python error in get_setting()

resources/lib/dbus_connman.py
Fix connman autoconnect is always disabled when saved.
Reported multiple times in the forum, e.g.:
https://forum.libreelec.tv/thread/24297-9-97-1-rpi4-ethernet-issue/
https://forum.libreelec.tv/thread/24271-libreleec-9-97-1-10-0-matrix-networking-not-connecting-automatically/
=> service_set_autoconnect(): check used parameters '0' and '1'

resources/language/resource.language.it_it/strings.po
This fixes it_it language.
It contains an extra `"` introduced here: 
https://github.com/LibreELEC/service.libreelec.settings/pull/262/files#diff-a59f2957e4233e6231d9ed22a2a1ed668d3815f1e1624f86814e1f96074eb724R60
@CvH @chewitt Please merge https://github.com/LibreELEC/service.libreelec.settings/pull/267 first.
Weblate will probably do a new PR after merging this PR.
=> Fix it_it language

resources/lib/modules/updates.py
This updates the addon to allow manual updates to work with nightly images off test.libreelec.tv.
The first five commits are cleanups, mostly around logging and if tests.
The sixth commit is an enhancement to add "https://" to a Custom URL if the string doesn't start with http:// or https://. Ex: I can put `test.libreelec.tv` as the Custom URL, as it'll correct it to `https://test.libreelec.tv/releases.json`.
The seventh commit updates the list of available builds in the releases.json displayed to users to account for it having images in addition to tarballs.
The eighth commit changes what `get_available_builds()` returns when given an argument from the build's name to the build's subpath+name. This is only used when combining with the URL from the releases.json in `do_manual_update()`. …
=> Rework manual update for new infrastructure

resources/lib/modules/updates.py
In addition to removing a loop in `get_available_builds()`, this also avoids potentially mangling what the prettyname_regex generates as the 'name' as only applying it during the filename fallback.
=> updates.py: remove a loop in get_available_builds

resources/lib/dbus_utils.py, resources/lib/modules/bluetooth.py, resources/lib/modules/connman.py
Some fixes, mostly oneliner.
BUS can be used in manager_unregister_agent()
Fix for:
```
2022-09-17 19:04:32.815 T:1363    error <general>: SETTINGS: Agent.unregister_agent 
*********************************** Unhandled exception detected ***********************************
####################################################################################################
Diagnostic info
----------------------------------------------------------------------------------------------------
Exception type  : DBusError
Exception value : org.freedesktop.DBus.Error.ServiceUnknown -- The name org.bluez was not provided by any .service files
System info     : uname_result(system='Linux', node='le10mars', release='5.10.142', version='#1 SMP Sat Sep 10 17:06:14 UTC 2022', machine='x86_64', …
```
=> Fixes, including working bluetooth PinKey window

resources/lib/modules/updates.py, resources/lib/oe.py
This alters the update channels users are able to select in manual updates by removing channels that belong to versions older than what the device is running. A device on LE10 will see the LE10 + LE11 channel, but not LE7 -> LE9, for example.
This exposes `/etc/os-releases`'s VERSION_ID to the addon in order to establish the running version. I'm not sure why oe.VERSION was being set to VERSION_ID and then being changed to VERSION, if present. The implication is that VERSION wasn't always there. It's been in the image building at least 4 years, so it's present in releases that'll see this change.
This relies on the naming scheme of LE's release.json's channels, so a custom channel may bypass it. The filter is simple, comparing a channel named `$something-$version` and checking `$version` …
=> Filter Update channels older than current version

resources/lib/config.py, resources/lib/dbus_bluez.py, resources/lib/dbus_connman.py, resources/lib/dbus_obex.py, resources/lib/dbus_utils.py, resources/lib/debug_utils.py, resources/lib/hostname.py, resources/lib/log.py, resources/lib/modules.py, resources/lib/modules/bluetooth.py, resources/lib/modules/connman.py, resources/lib/modules/services.py, resources/lib/modules/system.py, resources/lib/modules/updates.py, resources/lib/oe.py, resources/lib/oeWindows.py, resources/lib/os_tools.py, resources/lib/regdomain.py, resources/lib/ui_tools.py, syspath.py
This cleanup pass does: 
converts bluetooth.py to use log.log
converts oe.py and oeWindows.py to use the log.log_function decorator / log.log
removes oe.dbg_log
cleanup other oe.py functions
Everything should still be working in the same general way. No intentional changes were made to how functions were used. I've tested some of the addon, but I don't use all of its features so issues may be lurking.
=> oe.py cleanup pass

resources/lib/modules/updates.py
Updates.py has an update thread that:
1) Checks if media is playing and do nothing if True (check for update if false).
2) If an update isn't in progress, wait 6 hours and check again.
3) If an update is in progress (`update_in_progress` is set in addon), display a notification and wait 1 hour to display again.
`update_in_progress` can be set for a few reasons, but the typical is that autoupdate has downloaded an update and the device has not yet rebooted to apply the update.
This changes 3) to only display if no media is playing. The 1 hour wait to display again remains. Its update notification message could read "Update Waiting to Apply" or similar to remove ambiguity on what "available" means, but that can be a later PR.
=> updates.py: disable update notifications if media is playing

resources/lib/defaults.py, resources/lib/modules/services.py, resources/lib/oe.py
This PR contains two samba server related fixes reported in the forum.
[First report](https://forum.libreelec.tv/thread/26942-samba-service-query-about-default-settings-and-users/) shows that samba configuration is not updated until reboot - although smbd and nmbd are restarted. This is fixed by adding `samba-confiig.service` to the list of services to be reloaded.
In the [second issue reported](https://forum.libreelec.tv/thread/26994-samba-password-authentication/) samba user names and passwords are not escaped when saved and do fail when sourced by the samba-config shell script.  Simple solution is to escape any single character with functions sh_esc_str() and sh_unesc_str(). The second function is able to read previous not escaped strings too. Note that samba-config is compatible with …
=> samba reload config / samba escape saved strings / service handling

resources/lib/hostname.py
This rewrites most of hostname.set_hostname(). It's reduced to writing the hostname to a file, and then calling the network-base.service to set up hostname/hosts/resolv.conf as needed again. The writing hostname to file is changed so that it's only written to file if the hostname is different than what is currently in the file. Pre-PR it's writing the hostname everytime the system boots / kodi starts regardless of what's in the file already, so this gets rid of a useless write.
Merge after https://github.com/LibreELEC/LibreELEC.tv/pull/7696
=> hostname.py: use network-base.service for /etc/hosts editing

resources/lib/modules/updates.py
The addon will attempt to autocomplete a URL to retrieve releases.json from, so 'test.libreelec.tv' becomes 'https://test.libreelec.tv/releases.json'. 
This relaxes a test for adding '/releases.json' at the end to checking if it doesn't end with '.json' instead. This avoids mandating the json file's name to be 'releases.json', permitting something like 'releases_v2.json' or 'releases-for-my-project.json'.
While this shouldn't be needed in the long term, it doesn't get in the way and may make life easier in the short term.
Motivated by https://forum.libreelec.tv/thread/27101-empty-list-under-available-versions/?postID=180474
=> updates.py: relax releases.json url autocompletion

resources/lib/modules/updates.py
Similar reason like #299. Simplify testing with a local releases.json via Custom Channel like "file:///storage" instead of setting up a HTTP server.
=> update: allow local releases.json via "file://" for testing

resources/lib/hostname.py
Creates `/storage/.cache/hostname` on new installs. Does some cleanup too.
Resolves https://forum.libreelec.tv/thread/27162-system-name-always-reverts-to-libreelec-after-reboot/
=> hostnames: create on clean install

resources/lib/modules/updates.py
This is a cleanup of the listing of builds / build selection when using manual updates -> available versions. There should be no change in user experience.
=> updates.py: replace many try statements in get_available_builds

resources/lib/modules/system.py, resources/lib/modules/updates.py, resources/lib/os_tools.py
This is to keep behavior of previous oe.execute()
Needs testing.
=> os_tools: execute: return empty string on failure

resources/lib/defaults.py, resources/lib/modules/updates.py, resources/lib/oe.py
This changes the RPi firmware update process to depend on the presence of `rpi-eeprom-update` instead of a specific model (vl805 firmware reporting is hidden if not on RPi4). If an update is available, it uses `-A` to update the bootloader or vl805 individually and directs the user to reboot. The flashing trigger / special bootup is no longer used.
Tested on RPi5; vl805 related changes are untested.
One bug found in `rpi-eeprom-update`. If an update is available, then `rpi-eeprom-update` has a non-zero return value when called either by itself, or with the `-j` and `-m` options. Python reported a Bad File Descriptor as the reason. `-A` did not have an issue. 
Toggling an update on/off quickly crashed Kodi. No investigation done (I was trying to break it and succeeded...)
TODO …
=> Add support for RPi5 firmware updating

resources/lib/modules/bluetooth.py
This PF fixes the following issues:
* When a device is added to/removed from the list of BT devices, the list fully is fully refreshed and the selection is reset to the first position in the list.
* When all BT devices in the vicinity of a LE instance have been turned off, they stay in the list while the label for the empty list is displayed.
Now devices are added to/removed from the list of BT devices without fully refreshing the list and the currently selected item is restored (it is actually reset even when the list is not fully refreshed but items are added/removed).
This PR is supposed to fix the problem that we had at this year FOSDEM when we couldn't connect a LE device to a wireless speaker because the list displayed dozens of devices (we had dozens and even hundreds of people …
=> Optimize refreshing the list of Bluetooth devices

resources/lib/oe.py
imp has been dropped from Python 3.12, replace with importlib
https://github.com/LibreELEC/LibreELEC.tv/pull/9218
=> oe.py: update imp to importlib

resources/lib/hostname.py, resources/lib/modules/system.py
Noticed impossibility to change hostname, the old one was always kept
In addition  avahi and wsdd2 do keep old hostname until restated.
=> Fix broken hostname change / restart avahi and wsdd2 after change if running

resources/lib/hostname.py
avahi and wsdd2 do keep old hostname until restated.
Partial backport of #326
=> Restart avahi and wsdd2 after hostname change if running

resources/lib/dbus_utils.py
This is my understanding of what the addon needs for Python 3.13: https://github.com/LibreELEC/LibreELEC.tv/pull/9374
asyncio.get_event_loop() raises a RuntimeError if there isn't a loop running when it's called. This handles that error by creating a loop when it doesn't find one.
This is my best guess at the correct thing to do. I'm not familiar with asyncio. However, the addon Works For Me.
=> dbus_utils.py: adjust use of get_event_loop for its deprecation

resources/lib/oe.py
This is required after the LEIoT changes unbranded the variables in `/etc/os-release`
=> fix get_os_release after distro unbranding changes

resources/lib/modules/system.py, resources/lib/timezone.py
This adds deprecated or repeated timezones in tzdata to the addon's timezone selection. The sheer number of timezones are less of an issue with the addon remembering placement now.
Also adds additional logging around selecting a timezone and writing the selection to file for an issue where selection fails for reasons I don't know and can't repeat. 
Both issues mentioned in https://forum.libreelec.tv/thread/29491-timezone-missing-from-today-s-libreelec-nightly/
=> Improvements to timezone selection

resources/lib/modules/system.py, resources/lib/timezone.py
Builds on #331. This should be complete. Draft until that is merged.
This adds a function to guess a device's timezone based on its public ip. Public IP and the geoip lookup are provided by two webservices, icanhazip.com and ipapi.co. If a user has selected a timezone other than the default 'UTC', then it performs a lookup of the timezone associated with the device's ip and preselects it if it's in the list of available timezones. If the query fails, or the timezone isn't there, then it doesn't preselect anything. Once a user selects something other than the default, then it no longer guesses when opening the menu.
I expect this to be as good as timezone selection within Kodi will get without having a mechanism to tell Kodi the system's time changed. The alternative is having a service …
=> Add a timezone guess based on a device's IP

resources/lib/os_tools.py
These is a cleanup of os_tools's read_shell_setting() and read_shell_settings(). Most are pylint changes (document, don't override python builtin names, don't initialize a blank dictionary as a function's default), and readability. One functional change is for the functions to ignore commented lines.
There should be nothing visible to end users here. This is just cleaning them up for further use in more places in the addon.
=> Cleanups in os_tools.py

resources/lib/modules/system.py
This is a cleanup to replace a try/except with an if on deleting a file, and replacing multiple writes with a single f-string for creating the config for a persistent journal.
@mglae can review? I believe you wrote the original function.
=> Cleanup setting persistent journal config file
