LibreELEC/service.libreelec.settings

src/resources/lib/modules/system.py

needed for using .img.gz update method

updater: don't extract the file, let the update mechanism do the work

---

src/oe.py

Sorry about the dirty pull request. As much as I use github it still confuses me.

copy old openelec settings config for migration

---

Makefile
changelog.txt

this bumps the version to 0.7.0 and updates the changelog for recent updates

bump to v0.7.0

---

language/English/strings.po
src/resources/lib/modules/system.py

Please give a thorough review before merging.
Please check the new strings.

allow using update channels

---

src/resources/lib/modules/services.py

set the samba default to enabled at the wizard

enable samba at wizard

---

language/English/strings.po
skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml
src/resources/lib/modules/system.py

Original credit to @HitcherUK for the About text fix and Gordon from @FiveNinjas for the Log pastebin function

Fix 'About' text and add http://sprunge.us pastebin function

---

language/English/strings.po
src/resources/lib/modules/system.py
src/resources/lib/oeWindows.py

Could probably use a test build for people before releasing
I did a test and it seemed to work ok.

allow using update channels (libreelec-7.0 backport)

---

src/resources/lib/modules/system.py

fix blank system screen when no network is present

---

Makefile

Needed for non Estuary skins.
See: [https://forum.libreelec.tv/thread-2746.html](https://forum.libreelec.tv/thread-2746.html)

copy bg.jpg when installing

---

src/defaults.py

Needed by samba 4.6.0 change in LE master - see https://github.com/LibreELEC/LibreELEC.tv/pull/1469

change smbd and nmbd location

---

Makefile
changelog.txt
language/Bulgarian/strings.po
language/Czech/strings.po
language/Dutch/strings.po
language/French/strings.po
language/German/strings.po
language/Italian/strings.po
language/Lithuanian/strings.po
language/Norwegian/strings.po
language/Portuguese (Brazil)/strings.po
language/Russian/strings.po
language/Swedish/strings.po

these are the updated lang files from transifex (that are 100%)

update language from transifex

---

src/defaults.py
src/resources/lib/modules/services.py

merge together with https://github.com/LibreELEC/LibreELEC.tv/pull/1320

lircd: settings changes required for LE PR 1320

---

src/defaults.py

Temporarily revert the samba changes until Samba in LE master is bumped

Revert "change smbd and nmbd location"

---

language/Bulgarian/strings.po
language/Czech/strings.po
language/Dutch/strings.po
language/French/strings.po
language/German/strings.po
language/Italian/strings.po
language/Lithuanian/strings.po
language/Norwegian/strings.po
language/Portuguese (Brazil)/strings.po
language/Russian/strings.po
language/Swedish/strings.po

update language from transifex [master]

---

src/defaults.py

This has a dependency on https://github.com/LibreELEC/LibreELEC.tv/pull/1628. Merge them together.

change smbd and nmbd location [backport]

---

src/defaults.py

Reverts LibreELEC/service.libreelec.settings#68

revert "change smbd and nmbd location [backport]"

---

src/defaults.py

This reverts commit 57f3df00420904ec4709c8ba9c018987487850d7.
This has a dependency on https://github.com/LibreELEC/LibreELEC.tv/pull/1469 - they both need to merge together...

Revert "Revert "change smbd and nmbd location""

---

src/default.py

service: fix icon path [backport]

---

src/oe.py
src/resources/lib/modules/bluetooth.py

bluetooth: avoid race during disable [backport]

---

src/resources/lib/modules/system.py

backup folder size fix

---

language/English/strings.po
skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml
skins/Default/1080i/service-LibreELEC-Settings-wizard.xml
src/defaults.py
src/oe.py
src/resources/lib/modules/system.py

Replace CPU flag with GPU flag. Knowing if the CPU arch is 32-bit or 64-bit is now largely redundant information. Having a handle on how many Nvidia or AMD or Intel GPU installations we have is far more relevant/useful.
Much of this is blind, due to lack of hardware. I've tested it with i915-based Skylake NUC and ION2 based Revo3700 (Nvidia-legacy). VM (vmwgfx) should also be working. I haven't tested with any AMD hardware.
This may not work reliably with multi-GPU setups - hopefully it will just default to the first connected GPU.
To test:
1. enable `debugging` in kernel config
2. `grep -E "check_updates_v2|load_value|get_gpu" /storage/.kodi/temp/kodi.log`
```
18:11:14.627 T:140215976978176   DEBUG: ## LibreELEC Addon ## system::load_values ## enter_function
18:11:14.627 …
```

stats: Replace CPU 32/64 bit flag with GPU enumeration

---

language/English/strings.po
src/defaults.py
src/resources/lib/modules/bluetooth.py
src/resources/lib/modules/connman.py
src/resources/lib/modules/services.py
src/resources/lib/modules/system.py
src/resources/lib/modules/updates.py

This moves Updates into it's own menu - out of the System menu.
Hopefully I've removed the unnecessary lines from both modules - but a second set of eyes wouldn't hurt.

Updates menu

---

language/resource.language.en_gb/strings.po

Before (ignore that it's safe mode - text is the same):
After:

improve wording of Thank You page

---

language/resource.language.en_gb/strings.po
skins/Default/1080i/service-LibreELEC-Settings-wizard.xml
src/oe.py
src/resources/lib/modules/connman.py
src/resources/lib/modules/services.py
src/resources/lib/oeWindows.py

This adds an option to change the language during the first run wizard.  After the wizard completes it will also set the system to the new language.

Language option in first run wizard

---

language/resource.language.en_gb/strings.po

Fix a path in a help text

---

language/resource.language.en_gb/strings.po
src/oe.py
src/resources/lib/modules/system.py

Adds an option to LE settings to set a PIN lock for access.
Option is located under System menu.
After 3 failed PIN attempts, forces user to wait 5 minutes before trying again.

add PIN lock option to LE Settings

---

src/resources/lib/modules/updates.py

[OK] to continue, exit/back to abort.

updates: notify user if custom url is not accessible

---

src/resources/lib/modules/system.py

Move all the pastebin logic to `pastekodi`/`pastecrash` scripts.

Use pastekodi/pastecrash scripts

---

src/resources/lib/modules/updates.py

Adds support for vl805 (VIA USB3) firmware updating.

update to support vl805

---

.gitignore
Makefile
addon.xml
src/default.py
src/oe.py
src/resources/lib/modules/about.py
src/resources/lib/modules/bluetooth.py
src/resources/lib/modules/connman.py
src/resources/lib/modules/services.py
src/resources/lib/modules/system.py
src/resources/lib/modules/updates.py
src/resources/lib/modules/xdbus.py
src/resources/lib/oeWindows.py
src/service.py

This is the initial Py3 conversion for LE Settings.
~~Bluetooth is broken due to dbus issue - but~~ everything ~~else~~ should work for testing.

Py3 conversion

---

language/resource.language.en_gb/strings.po
src/resources/lib/modules/bluetooth.py
src/resources/lib/modules/services.py
src/service.py

To save battery power:
- Make the standby feature work with kodi's dpms feature
- New gui setting for an idle timeout

Bluetooth improvements

---

language/resource.language.en_gb/strings.po

I've never been a fan of "Raspberry Pi Flashing" as a description, so I'd like to change it.

improve update section titles

---

src/oe.py

improve download performance on fast connections [backport]

---

language/resource.language.en_gb/strings.po
src/resources/lib/modules/connman.py

adds backport of custom regdom setting

Add custom regdom option

---

src/resources/lib/modules/connman.py

* Code cleanup to avoid duplicating filenames / defaults
* Uses standard Python to delete and write files (rather than using shell code)
Could be backported as part of #154, but not essential.

Regdomain cleanup

---

src/oe.py

Reported on forum: https://forum.kodi.tv/showthread.php?tid=343069&pid=2940184#pid2940184

Fix potential divide by zero errors

---

src/oe.py
src/resources/lib/modules/bluetooth.py
src/resources/lib/modules/connman.py
src/resources/lib/modules/system.py
src/resources/lib/modules/updates.py
src/resources/lib/oeWindows.py

Fixup API changes after https://github.com/xbmc/xbmc/pull/17456

Fix Python API changes

---

language/resource.language.en_gb/strings.po
src/oe.py
src/resources/lib/modules/system.py

PIN cleanup

---

src/oe.py

Fix potential divide by zero errors [backport]

---

skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml
skins/Default/1080i/service-LibreELEC-Settings-wizard.xml

Noticed a texture path error while working on the wifi cache issue

Fix missing texture path

---

src/resources/lib/bus.py
src/resources/lib/config.py
src/resources/lib/modules/connman.py
src/resources/lib/modules/xdbus.py

This is a good start, but there is a long way to go

Switch to ravel

---

src/resources/lib/modules/about.py

This tidies about.py and converts some connman.py from dbus to ravel

connman.py: convert further calls to ravel

---

src/resources/lib/config.py
src/resources/lib/dbus_connman.py
src/resources/lib/dbus_utils.py
src/resources/lib/modules/connman.py

This works, somehow, but is still work in progress
Do not merge

connman.py: prepare agent

---

src/resources/lib/dbus_utils.py
src/resources/lib/modules/connman.py

This was missing from my previous pull request

connman.py: wait for future to avoid crashes

---

src/resources/lib/modules/bluetooth.py

use log decorator
directly refer to oe

bluetooth.py: cleanup

---

src/resources/lib/modules/updates.py

backport of #182 with minor changes for 9.2 branch, depends on https://github.com/LibreELEC/LibreELEC.tv/pull/4675

use dtflag helper for all arm board stats

---

resources/lib/config.py
resources/lib/dbus_bluez.py
resources/lib/dbus_connman.py
resources/lib/dbus_utils.py
resources/lib/hostname.py
resources/lib/modules/bluetooth.py
resources/lib/modules/connman.py
resources/lib/modules/system.py
resources/lib/oe.py
resources/lib/os_tools.py
resources/lib/regdomain.py
resources/lib/ui_tools.py

I submit this pull request to indicate that I am working on bluetooth settings
The changes do not break the settings add-on
They unfortunately do not fix it either
Work in progress, thus

bluetooth.py: migrate to ravel

---

resources/lib/dbus_utils.py
resources/lib/modules/updates.py
service.py

cosmetic changes:
directly refer to oe
use log_function decorator
move data out of code

updates.py: cleanup

---

resources/lib/modules/connman.py

Settings change required by LibreELEC/LibreELEC.tv#4802.

Enable Wait On Network by default (need change in service).

---

resources/lib/dbus_bluez.py
resources/lib/dbus_connman.py
resources/lib/dbus_obex.py
resources/lib/dbus_utils.py
resources/lib/modules/bluetooth.py
resources/lib/modules/connman.py

bluetooth.py: migrate agents to ravel

---

resources/lib/dbus_connman.py
resources/lib/dbus_utils.py
resources/lib/modules/bluetooth.py

Fix wrong INFO level debugging.
See: https://github.com/LibreELEC/service.libreelec.settings/pull/212#issuecomment-789155790

Use only debug logging for @log.log_function()

---

src/oe.py

Use LOGINFO for download_file and LOGDEBUG for copy_file()
Extended backport of #183

Fix status log messages using LOGERROR

---

resources/lib/modules/bluetooth.py

This PR fixes the logic of running the Bluetooth discovery thread. It also includes some refactoring of the BT module.

Fix the logic of running the BT discovery thread
